SWM-Codection/gitea

options/locale/locale_ko-KR.ini
=> 이슈 및 기타 리다이렉트 링크 수정

models/issues/issue_search.go, modules/indexer/issues/dboptions.go, modules/indexer/issues/internal/model.go, options/locale/locale_en-US.ini, routers/web/repo/issue.go, routers/web/repo/milestone.go, routers/web/web.go, templates/repo/header.tmpl, templates/repo/issue/openclose.tmpl
=> Discussion 프론트엔드 기능 추가..

templates/repo/issue/view_content/sidebar.tmpl
resolve #12
추가 사항 있으시면 의견 남겨주세요
dependency 의 경우 + 를 그대로 유지했습니다
=> #12 업데이트 이미지 변경 수정 

models/issues/issue_search.go, models/issues/issue_stats.go, modules/indexer/issues/dboptions.go, modules/indexer/issues/internal/model.go, options/locale/locale_en-US.ini, options/locale/locale_ko-KR.ini, routers/web/repo/issue.go, routers/web/repo/milestone.go, routers/web/web.go, templates/repo/header.tmpl, templates/repo/issue/list.tmpl, templates/repo/issue/openclose.tmpl
=> #11 discussion 페이지 표기 오류 수정

models/issues/issue_search.go, models/issues/issue_stats.go, modules/indexer/issues/dboptions.go, modules/indexer/issues/internal/model.go, options/locale/locale_en-US.ini, options/locale/locale_ko-KR.ini, routers/web/repo/issue.go, routers/web/repo/milestone.go, routers/web/web.go, templates/repo/header.tmpl, templates/repo/issue/list.tmpl, templates/repo/issue/openclose.tmpl
Reverts SWM-Codection/gitea#14
=> Revert "#11 discussion 페이지 표기 오류 수정"

models/issues/issue_stats.go, options/locale/locale_en-US.ini, options/locale/locale_ko-KR.ini, templates/repo/issue/list.tmpl
=> Feature/discussion err#11

client/discussion/discussion_client.go, templates/repo/discussion/view.tmpl, web_src/js/components/DiscussionCodeLineSelector.vue
- 디스커션 인덱스 문제 해결
- 디스커션 코드 뷰에서 파일 이동 해결
=> 프론트 사소한 수정

web_src/js/components/DiscussionCodeLineSelector.vue
한 일
---
- 코멘트 작성 시 한 번도 드래그를 하지 않은 상태에서 코멘트 폼 작성 버튼 클릭을 할 경우 버그가 발생하는 부분 해결
=> fix: 코멘트 작성 버그 수정

routers/web/repo/highlight_download.go, web_src/js/components/DiscussionForm.vue
맨처음엔 파일 트리에서 아예 배제할까 하다가.. 
어차피 파일 내용물 볼때 읽기가한번은일어나기 때문에 그때 반환하는걸로 바꿨습니다
=> [VIR-177] 바이너리 파일 필터

web_src/js/components/DiscussionCodeLineSelector.vue, web_src/js/components/DiscussionFileCodeLine.vue
한 일
---
1. 기존에 비대했던 DiscussionCodeLineSelector에서 DIscussionFileCodeLine을 분리
2. DiscussionCodeLineSelector의 전반적인 코드 리팩토링
추가 리팩토링 예정
---
CommentForm 부분이랑 Comment 관련 부분 분리 예정
아예 파일 이름을 DiscussionFile로 바꾸고 코드 선택 관련된 부분을 mixin으로 뺄 예정
현재 리팩토링은 우선 순위가 낮다고 판단돼서 추가적인 리팩토링은 나중에 할듯
=> refactor: DiscussionCodeLineSelector에서 DiscussionFileCodeLine 분리

templates/repo/discussion/discussionlist.tmpl
마감 된 디스커션시 프론트에서 문제 발생하는 코드 제거
=> 디스커션 데드라인 버그

models/issues/ai_comment.go, models/issues/comment_code.go
저장은 Pull Request의 Id로 했으나 가져오는 로직은 Issue의 Id로 가져와서 제대로 된 리뷰를 가져오지 못하는 이슈 해결
=> solve ai pull comment issue

LICENSE
=> [VIR-194] update license authors

templates/user/dashboard/feeds.tmpl, templates/user/heatmap.tmpl
=> [vir-192] empty repo feed

templates/repo/diff/box.tmpl
=> [VIR-187] change sample code loading to spinner

README.md
=> 리드미 이미지 불변 주소로 수정

services/ai/requester.go, services/ai/sample_code.go, web_src/js/features/repo-ai-samplecode.js
=> AI 샘플코드 마크다운 프리뷰

client/discussion/discussion_client.go, services/discussion/discussion.go
close #99 
SWM-Codection/Codection-Review-Service#47 이 병합되어야 적용 가능합니다
=> [VIR-167] 디스커션 정렬 기능 

web_src/js/features/discussion-file-comment.js
한 일
---
디스커션  파일 클릭시 코멘트 하이라이트 기능 추가
https://github.com/user-attachments/assets/e4ae6104-50f6-4e73-9ab8-b4e7db9d27f4
참고로 한 코멘트에 달린 답변은 모두 같은 startLine과 endLine에 코멘트인 걸로 칩니다.
=> feat: 디스커션 파일 코멘트 하이라이트 기능 추가

client/discussion/discussion_client.go, routers/web/repo/discussion.go, routers/web/web.go, templates/repo/discussion/reactions.tmpl, templates/repo/discussion/view_conversation.tmpl, web_src/js/features/discussion-general-comment.js, web_src/js/index.js
closes #101 
추가로 백엔드의 SWM-Codection/Codection-Review-Service#51 이 완료되어야 기능이 적용 가능합니다
ReactionList 의 경우 discussion_client 로 위치가 변경되었습니다
=> [VIR-199] 리액션 기능 추가

client/discussion/discussion_client.go, routers/web/repo/discussion.go, routers/web/repo/issue_pin.go, routers/web/web.go, services/discussion/discussion.go, templates/repo/discussion/card.tmpl, templates/repo/discussion/list.tmpl, templates/repo/issue/view_content/discussion_sidebar.tmpl, templates/shared/discussionicon.tmpl
###구현한 기능
- 디스커션 상세 페이지
pin/unpin 기능
- 디스커션 리스트 페이지
pin 된 디스커션 카드 리스트
unpin 기능
드래그 앤 드랍으로 순위 재지정
구현 된 로직에 대한 설명은 아래를 참고하세요
https://github.com/SWM-Codection/Codection-Review-Service/pull/60
discussionResponse에 pinOrder 컬럼을 추가하고 위의 정의 된 기능을 구현하였습니다.
※ 위의 Review-Service를 동작 시키고 실행해야만 합니다!
5. 결과(optional)
6. 회고(optional)
=> [VIR-205] 디스커션 Pin 기능

models/discussion/sample_code.go, routers/web/repo/discussion.go, routers/web/web.go, services/ai/sample_code.go, services/discussion/discussion.go, templates/repo/discussion/context_menu.tmpl, templates/repo/discussion/file_comment.tmpl, web_src/js/components/DiscussionCodeLineSelector.vue, web_src/js/components/DiscussionFileCommentOption.vue, web_src/js/components/DiscussionFileDetail.vue, web_src/js/features/discussion-file-comment.js
1. ai 코멘트 수정 기능 추가
2. ai 코멘트 수정, 삭제를 코멘트를 생성한 사람만이 수정할 수 있도록 권한 설정
3. 기존에 작동하지 않았던 디스커션 코멘트 링크 복사 기능 복구
추후 권한 설정에 대한 수정이 필요해보임.
=> [VIR-211] ai 코멘트 수정 기능 

models/repo.go, models/repo/repo.go, routers/web/repo/discussion.go, services/discussion/discussion.go, templates/repo/header.tmpl
위의 이미지와 같이 discussion의 수를 표기 해주는 title바 코드가 누락되어 추가함
=> discussion 갯수 preview

modules/setting/ai_server.go
ConfigParser 가 Case Sensitive 해서 지금껏 ai 서버로 정상적이 요청이 가지 못했습니다..
=> fix: modify ai_server host key

client/discussion/discussion_client.go, client/discussion/model/delete_discussion_request.go, routers/web/repo/discussion.go, routers/web/web.go, templates/repo/issue/filter_actions.tmpl
=> discussion 삭제 구현
